#!/bin/bash
### BEGIN INIT INFO
# Provides:          perl-fcgi
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the Perl FastCGI daemon.
### END INIT INFO
PERL_SCRIPT=/usr/local/bin/fastcgi-wrapper.pl
FASTCGI_USER=www-data
RETVAL=0
case "$1" in
    start)
      sudo -u $FASTCGI_USER -H $PERL_SCRIPT
      RETVAL=$?
      echo "otrs fast-cgi started."
  ;;
    stop)
      killall -9 fastcgi-wrapper.pl
      RETVAL=$?
      echo "otrs fast-cgi stopped."
  ;;
    restart)
      killall -9 fastcgi-wrapper.pl
      sudo -u $FASTCGI_USER -H $PERL_SCRIPT
      RETVAL=$?
      echo "otrs fast-cgi restarted"
  ;;
    *)
      echo "Usage: perl-fcgi {start|stop|restart}"
      exit 1
  ;;
esac
exit $RETVAL
